# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_hash_func <- function(keys, num_slots = 9L) {
    invisible(.Call('hgen488_simple_hash_fn', PACKAGE = 'hgen488', keys, num_slots))
}

two_stack_fun <- function(keys, pushStackA, popStackA) {
    invisible(.Call('hgen488_two_stacks_fn', PACKAGE = 'hgen488', keys, pushStackA, popStackA))
}

rcppeigen_hello_world <- function() {
    .Call('hgen488_rcppeigen_hello_world', PACKAGE = 'hgen488')
}

rcppeigen_outerproduct <- function(x) {
    .Call('hgen488_rcppeigen_outerproduct', PACKAGE = 'hgen488', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('hgen488_rcppeigen_innerproduct', PACKAGE = 'hgen488', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('hgen488_rcppeigen_bothproducts', PACKAGE = 'hgen488', x)
}

