# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mat_mult <- function(A, B) {
    .Call('hgen488_mat_mult', PACKAGE = 'hgen488', A, B)
}

mat_mult_eigen <- function(A, B) {
    .Call('hgen488_mat_mult_eigen', PACKAGE = 'hgen488', A, B)
}

rep_mat_mult_eigen <- function(A, B, reps) {
    .Call('hgen488_rep_mat_mult_eigen', PACKAGE = 'hgen488', A, B, reps)
}

GramSchmidt <- function(X) {
    .Call('hgen488_GramSchmidt', PACKAGE = 'hgen488', X)
}

GramSchmidtQR <- function(X) {
    .Call('hgen488_GramSchmidtQR', PACKAGE = 'hgen488', X)
}

GramSchmidtSVD <- function(X) {
    .Call('hgen488_GramSchmidtSVD', PACKAGE = 'hgen488', X)
}

GramSchmidtPCA <- function(X) {
    .Call('hgen488_GramSchmidtPCA', PACKAGE = 'hgen488', X)
}

sample_hash_func <- function(keys, num_slots = 9L) {
    invisible(.Call('hgen488_simple_hash_fn', PACKAGE = 'hgen488', keys, num_slots))
}

two_stack_fun <- function(keys, pushStackA, popStackA) {
    invisible(.Call('hgen488_two_stacks_fn', PACKAGE = 'hgen488', keys, pushStackA, popStackA))
}

rcppeigen_hello_world <- function() {
    .Call('hgen488_rcppeigen_hello_world', PACKAGE = 'hgen488')
}

rcppeigen_outerproduct <- function(x) {
    .Call('hgen488_rcppeigen_outerproduct', PACKAGE = 'hgen488', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('hgen488_rcppeigen_innerproduct', PACKAGE = 'hgen488', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('hgen488_rcppeigen_bothproducts', PACKAGE = 'hgen488', x)
}

